<?php

namespace Tests\Feature;

use Illuminate\Support\Facades\Hash;
use App\Hashing\ScryptHasher;
use Tests\TestCase;

class ScryptHasherTest extends TestCase
{
    public function test_check_validates_known_node_hash()
    {
        // Generated by Node.js crypto.scrypt('password', 'salt1234salt1234salt1234salt1234', 64)
        $saltHex = '73616c743132333473616c743132333473616c743132333473616c7431323334'; // Actually, in my Node test I used the string 'salt1234salt1234salt1234salt1234', which hex encoded is this.

        // Wait, Node code: crypto.randomBytes(16).toString('hex') is a 32 character hex string.
        // Node's auth.js uses: `const salt = crypto.randomBytes(16).toString('hex');`
        // Then passes that `salt` string directly to `crypto.scrypt(password, salt, 64)`.

        $nodeSalt = '73616c743132333473616c7431323334'; // 32 characters
        $nodeDerived = 'd92167514d2b325592b30abf828594639712bab4ed4edb2484fc74ae701b8e82d91287634b6c1c739aa9f2132a9cb227c1b6bd244fa645c837ac0f376379c1dc'; // Output from my test! Wait, the salt in my test was 'salt1234salt1234salt1234salt1234' which is 32 characters!
        $password = 'password';

        // Actually wait, let's just use the exact string from my test.
        $testSaltString = 'salt1234salt1234salt1234salt1234';

        $hashStr = "scrypt:{$testSaltString}:{$nodeDerived}";

        $this->assertTrue(Hash::check($password, $hashStr));
    }

    public function test_make_generates_valid_scrypt_hash()
    {
        $password = 'secret-password';
        $hashed = (new ScryptHasher())->make($password);

        $this->assertStringStartsWith('scrypt:', $hashed);

        $parts = explode(':', $hashed);
        $this->assertCount(3, $parts);
        $this->assertEquals(32, strlen($parts[1]), 'Salt should be 32 hex characters');
        $this->assertEquals(128, strlen($parts[2]), 'Derived key should be 128 hex characters (64 bytes)');

        $this->assertTrue((new ScryptHasher())->check($password, $hashed));
        $this->assertFalse((new ScryptHasher())->check('wrong-password', $hashed));
    }

    public function test_flexible_hasher_uses_bcrypt_for_new_hashes()
    {
        $hashed = Hash::make('secret-password');

        $this->assertStringStartsWith('$2y$', $hashed);
        $this->assertTrue(Hash::check('secret-password', $hashed));
    }
}
